version: "2.1"

services:
  flaresolverr:
    build:
      context: .
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_FILE=none
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=Europe/London
    ports:
      - "8191:8191"
    volumes:
      - /var/lib/flaresolver:/config
    restart: unless-stopped
